name: PEP8 validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install autopep8

      - name: Fix PEP8 errors
        run: autopep8 --in-place --recursive .

      - name: Check PEP8 validation
        run: pycodestyle .

      - name: Fail if PEP8 validation errors
        if: steps.check-pep8.outputs.failed == 1
        uses: actions/github-script@v6
        with:
          script: |
            console.log("PEP8 validation errors found.")
            process.exit(1)
            
